name: Update WordPress Plugin

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  update-plugin:
    runs-on: ubuntu-latest
    env:
      WP_SITE_URL: ${{ secrets.WP_SITE_URL }}
      WP_USERNAME: ${{ secrets.WP_USERNAME }}
      WP_PASSWORD: ${{ secrets.WP_PASSWORD }}

    steps:
    - name: Get latest release
      id: get_release
      run: |
        RELEASE_DATA=$(curl -s https://api.github.com/repos/Nocs-lab/Obatala/releases/latest)
        ASSET_URL=$(echo "$RELEASE_DATA" | jq -r '.assets[] | select(.name == "obatala.zip") | .url')
        echo "ASSET_URL=$ASSET_URL" >> $GITHUB_ENV

    - name: Download the latest release
      run: |
        curl -L -o obatala.zip -H "Accept: application/octet-stream" "$ASSET_URL"

    - name: Upload the plugin to WordPress
      run: |
        curl -X POST "$WP_SITE_URL/wp-json/wp/v2/plugins/obatala" \
          -u "$WP_USERNAME:$WP_PASSWORD" \
          -F "file=@obatala.zip"

    - name: Activate the plugin
      run: |
        curl -X POST "$WP_SITE_URL/wp-json/wp/v2/plugins/obatala/activate" \
          -u "$WP_USERNAME:$WP_PASSWORD"
